RULE_DESCRIPTIONS = {
    'check_battery_and_terminals': 'Check the battery and terminals',
    'confirm_fuel_gas_level': 'Confirm the fuel gas level',
    'check_switching_operation': 'Check the switching operation',
    'contact_experienced_personnel': 'Contact experienced personnel',
    'change_fuel_pump': 'Change the fuel pump',
    'check_and_change_fuel_pump_fuse': 'Check and change the fuel pump fuse',
    'replace_slow_running_jet_with_help': 'Replace the slow running jet with help',
    'check_vehicle_battery': 'Check the vehicle battery',
    'charge_battery': 'Charge the battery',
    'check_test_starter': 'Check the test starter',
    'replace_battery': 'Replace the battery',
    'replace_battery_and_starter_with_help': 'Replace the battery and starter with help',
    'check_spark_plug_and_contact_set': 'Check the spark plug and contact set',
    'contact_experienced_personnel_for_major_fault': 'Contact experienced personnel for major fault',
    'check_overheating_water_level_and_radiator_fan': 'Check overheating, water level, and radiator fan',
    'stop_vehicle_cool_engine': 'Stop the vehicle and cool the engine',
    'check_engine_oil_leak_from_gasket_seals_and_connections': 'Check engine oil leak from gasket, seals, and connections',
    'check_exhaust_smoke_color': 'Check exhaust smoke color',
    'seek_assistance_for_black_or_gray_smoke': 'Seek assistance for black or gray smoke',
    'seek_assistance_for_blue_smoke': 'Seek assistance for blue smoke',
    'seek_assistance_for_white_smoke': 'Seek assistance for white smoke',
    'seek_assistance_for_excessive_engine_noise': 'Seek assistance for excessive engine noise',
    'seek_assistance_for_engine_knocking': 'Seek assistance for engine knocking',
    'check_exhaust_system_for_rattling': 'Check exhaust system for rattling',
    'check_air_filter_for_clogging': 'Check air filter for clogging',
    'inspect_distributor_and_ignition_coil': 'Inspect distributor and ignition coil',
    'seek_assistance_for_faulty_ignition_module': 'Seek assistance for faulty ignition module',
    'seek_assistance_for_faulty_spark_plug_wires': 'Seek assistance for faulty spark plug wires',
    'seek_assistance_for_faulty_distributor_cap': 'Seek assistance for faulty distributor cap',
    'check_engine_timing': 'Check engine timing',
    'seek_assistance_for_faulty_crankshaft_position_sensor': 'Seek assistance for faulty crankshaft position sensor',
    'check_exhaust_system_for_hissing': 'Check exhaust system for hissing',
    'seek_assistance_for_exhaust_leaks': 'Seek assistance for exhaust leaks',
    'check_fuel_injectors_for_clogging': 'Check fuel injectors for clogging',
    'seek_assistance_for_faulty_fuel_pressure_regulator': 'Seek assistance for faulty fuel pressure regulator',
    'seek_assistance_for_faulty_fuel_injectors': 'Seek assistance for faulty fuel injectors',
    'check_cooling_system_for_leaks': 'Check cooling system for leaks',
    'seek_assistance_for_faulty_water_pump': 'Seek assistance for faulty water pump',
    'seek_assistance_for_faulty_thermostat': 'Seek assistance for faulty thermostat',
    'seek_assistance_for_faulty_radiator_cap': 'Seek assistance for faulty radiator cap',
    'check_engine_oil_level_and_condition': 'Check engine oil level and condition',
    'check_coolant_level_and_radiator_condition': 'Check coolant level and radiator condition',
    'check_thermostat_operation': 'Check thermostat operation',
    'inspect_underneath_for_fluid_leaks': 'Inspect underneath for fluid leaks',
    'check_power_steering_fluid_level': 'Check power steering fluid level',
    'check_ac_refrigerant_level_and_compressor_operation': 'Check AC refrigerant level and compressor operation',
    'seek_assistance_for_faulty_ac_condenser': 'Seek assistance for faulty AC condenser',
    'seek_assistance_for_faulty_ac_blower_motor': 'Seek assistance for faulty AC blower motor',
    'check_dashboard_temperature_indicator': 'Check dashboard temperature indicator',
    'seek_assistance_for_faulty_cabin_temperature_sensor': 'Seek assistance for faulty cabin temperature sensor',
    'seek_assistance_for_faulty_heater_core': 'Seek assistance for faulty heater core',
    'seek_assistance_for_engine_backfiring' : 'Seek assistance for engine backfiring',
'seek_assistance_for_engine_surging': 'Seek assistance for engine surging',
'check_fuel_pressure':'Check fuel pressure',
'seek_assistance_for_faulty_fuel_pump_relay':'Seek assistance for faulty fuel pump relay'}